# -*- coding: utf-8 -*-
"""Association_Rules.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wIQ0mC54Bu3qWyDRNaR7HRweiQFYlpM
"""

import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori,association_rules

!pip install mlxtend

df = pd.read_csv("https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Titanic.csv")

df = pd.get_dummies(df)

df

scores =apriori(df,min_support=0.25,use_colnames=True)

model = association_rules(scores)

"""# *Supermarket*"""

df = pd.read_csv("https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Supermarket.csv",index_col=0)

df.iloc[[0]]

text = "milk,bread,sauce"

text.split(",")

data = [i.split() for i in df["Products"]]
data

from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()

en_df = te.fit_transform(data)

pd.DataFrame(en_df)

te.columns_

en_df = pd.DataFrame(en_df,columns=te.columns_)
en_df

en_df.replace(False,0,inplace=True)
en_df.replace(True,1,inplace=True)

en_df

scores = apriori(en_df,min_support=0.25,use_colnames=True) 
scores

model = association_rules(scores)
model



