# -*- coding: utf-8 -*-
"""RecommendationSystem .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGVjfI9gIx1y6KNYtmt3OiwFuaOXa_2T
"""

import pandas as pd
import numpy as nm
import seaborn as sns
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (10,5)
plt.rcParams['figure.dpi'] = 250
import warnings
warnings.filterwarnings('ignore')

#load the data
df = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/Movie.csv')
df

"""# ***EDA***"""

df.describe()

df["userId"].nunique()

# numpy work with only array format

df["movie"].nunique()

df["rating"].nunique()

"""# ***DATA visulization***"""

#countplot

sns.countplot(y = df["movie"])

sns.countplot(df["rating"])

#pie chart

df["movie"].value_counts().plot(kind="pie",autopct="%0.2f%%")
#autopct="%0.2f%% is for percentage

df["rating"].value_counts().plot(kind="pie",autopct = "%0.2f%%")

"""Comparession between movies and **ratings**"""

sns.catplot(data=df,x= "rating", col="movie",kind="count",col_wrap=2)

"""# ***Model Building***"""

df

pivot = pd.pivot(data=df,index="userId",columns="movie",values="rating")

pivot

pivot.fillna(0,inplace=True)

pivot

#calculate distance and similarity

from sklearn.metrics import pairwise_distances
dist = pairwise_distances(pivot,metric="cosine")
pd.DataFrame(dist)

sim = 1-pairwise_distances(pivot,metric="cosine")
sim = pd.DataFrame(sim)

sim

#it is needed because numpy is run in array only
sim.values

nm.fill_diagonal(sim.values,0)

sim

df["userId"]

#replacing index number with user id
sim.index = df["userId"].unique()
sim.columns = df["userId"].unique()

sim

users = pd.DataFrame(sim.idxmax())

users
#3 and 11 are similar users 
#similary 6 and 11 are similar user

users.reset_index(inplace=True)
users

users

users.columns = ["user1","user2"]

users

"""FINDOUT SIMILAR USER"""

#pandas filltering 
df[(df["userId"]==3) | (df["userId"]==11)]

df[(df["userId"]==7105) | (df["userId"]==4110)]

df[(df["userId"]==7044) | (df["userId"]==8)]











































